# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
rocprof Profiling Module for Triton Kernels on AMD GPUs.

This module wraps rocprof (AMD ROCm profiler) to collect hardware performance
counters for Triton kernels running on AMD GPUs. Supports both rocprof v1/v2
(``rocprof``) and rocprofiler-sdk (``rocprofv3``) CLI interfaces.

Counter Categories
------------------
- **SQ counters**: Shader processor activity (SQ_WAVES, SQ_INSTS_VALU, etc.)
- **TCC counters**: L2 cache / memory controller (TCC_HIT, TCC_MISS, etc.)
- **EA / GRBM counters**: Memory bandwidth and bus activity

The collected counters are mapped to a metric dictionary compatible with the
rest of the KernelAgent optimization pipeline.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

# ---------------------------------------------------------------------------
# Hardware counter sets collected via rocprof -i <input_file>
# ---------------------------------------------------------------------------

# PMC counters requested from the hardware.  Each line in the input file
# specifies one pass of the hardware; rocprof runs the kernel once per pass.
# Keep pass count low to avoid excessive re-runs.

# Pass 1: Wavefront / shader utilisation
_PMC_PASS1 = [
    "SQ_WAVES",  # total wavefronts launched
    "SQ_INSTS_VALU",  # VALU (vector ALU) instructions executed
    "SQ_INSTS_SALU",  # SALU (scalar ALU) instructions executed
    "SQ_INSTS_VMEM_RD",  # vector memory read instructions
    "SQ_INSTS_VMEM_WR",  # vector memory write instructions
    "SQ_INSTS_LDS",  # LDS instructions
    "SQ_WAIT_INST_ANY",  # stall cycles waiting on any instruction
]

# Pass 2: L2 cache activity
_PMC_PASS2 = [
    "TCC_HIT_sum",  # L2 cache hits (sum over all TCC slices)
    "TCC_MISS_sum",  # L2 cache misses
    "TCC_EA_RDREQ_sum",  # EA read requests (to HBM)
    "TCC_EA_WRREQ_sum",  # EA write requests (to HBM)
]

# Pass 3: Memory bandwidth (derived counters)
# FETCH_SIZE and WRITE_SIZE use the same internal hardware PMC block and
# cannot be collected together in a single pass on rocprofv3 / gfx942.
# Collecting them on separate lines avoids error 38 ("Request exceeds the
# capabilities of the hardware to collect") and the associated hang.
_PMC_PASS3 = [
    "FETCH_SIZE",  # bytes fetched from memory (in KB, vendor metric)
]

_PMC_PASS4 = [
    "WRITE_SIZE",  # bytes written to memory (in KB, vendor metric)
]

# Derived metric keys returned in the normalized metrics dict
ROCM_METRIC_KEYS = [
    "sq_waves",
    "sq_insts_valu",
    "sq_insts_salu",
    "sq_insts_vmem_rd",
    "sq_insts_vmem_wr",
    "sq_insts_lds",
    "sq_wait_inst_any",
    "tcc_hit",
    "tcc_miss",
    "tcc_cache_hit_rate_pct",
    "tcc_ea_rdreq",
    "tcc_ea_wrreq",
    "fetch_size_kb",
    "write_size_kb",
    # Derived
    "valu_utilization_pct",  # SQ_INSTS_VALU / (SQ_WAVES * max_valu_per_wave)
    "memory_bound_pct",  # heuristic: vmem instructions / total instructions
    "compute_sol_pct",  # heuristic compute SOL for roofline compat
    "memory_sol_pct",  # heuristic memory SOL for roofline compat
]


# ---------------------------------------------------------------------------
# rocprof input file generation
# ---------------------------------------------------------------------------


def _write_rocprof_input(output_dir: Path) -> Path:
    """Write a rocprof PMC input file requesting our counter passes.

    rocprof reads this file and schedules one hardware pass per ``pmc:`` line.
    Counter names listed on the same line are collected in a single pass.

    Args:
        output_dir: Directory to write the input file.

    Returns:
        Path to the written input file.
    """
    lines = [
        "# rocprof PMC input file — generated by KernelAgent",
        f"pmc: {' '.join(_PMC_PASS1)}",
        f"pmc: {' '.join(_PMC_PASS2)}",
        f"pmc: {' '.join(_PMC_PASS3)}",
        f"pmc: {' '.join(_PMC_PASS4)}",
    ]
    input_file = output_dir / "rocprof_input.txt"
    input_file.write_text("\n".join(lines) + "\n")
    return input_file


# ---------------------------------------------------------------------------
# rocprof invocation
# ---------------------------------------------------------------------------


def _find_rocprof() -> str:
    """Find the rocprof binary, preferring rocprofv3 when available."""
    for candidate in ("rocprofv3", "rocprof"):
        found = shutil.which(candidate)
        if found:
            return found
    # Fallback to common installation path
    for path in ("/opt/rocm/bin/rocprof", "/usr/bin/rocprof"):
        if Path(path).exists():
            return path
    raise FileNotFoundError(
        "rocprof binary not found. Install ROCm and ensure rocprof is on PATH."
    )


def profile_triton_kernel_rocm(
    benchmark_script: Path,
    workdir: Path,
    out_prefix: str = "rocprof_output",
    python_executable: Optional[str] = None,
    rocprof_bin: Optional[str] = None,
    timeout: int = 360,
) -> Path:
    """Profile a Triton kernel using rocprof.

    Runs the benchmark script twice:
    1. ``rocprof --stats`` — collects kernel timing (duration in ns).
    2. ``rocprof -i input.txt`` — collects hardware PMC counters.

    The two CSV outputs are merged into a single JSON metrics file.

    Args:
        benchmark_script: Path to the Python script that calls the kernel.
        workdir: Working directory for execution and output files.
        out_prefix: Prefix for output filenames.
        python_executable: Python executable (default: sys.executable).
        rocprof_bin: Path to rocprof binary (auto-detect if None).
        timeout: Timeout in seconds per rocprof invocation.

    Returns:
        Path to the merged JSON metrics file.

    Raises:
        FileNotFoundError: If rocprof binary or benchmark script not found.
        RuntimeError: If rocprof profiling fails.
    """
    if python_executable is None:
        python_executable = sys.executable

    if rocprof_bin is None:
        rocprof_bin = _find_rocprof()

    benchmark_script = benchmark_script.resolve()
    if not benchmark_script.exists():
        raise FileNotFoundError(f"Benchmark script not found: {benchmark_script}")

    workdir = workdir.resolve()
    workdir.mkdir(parents=True, exist_ok=True)

    env = os.environ.copy()
    env["TRITON_CACHE_DIR"] = str(workdir / ".triton_cache")

    stats_csv = workdir / f"{out_prefix}_stats.csv"
    pmc_csv = workdir / f"{out_prefix}_pmc.csv"
    metrics_json = workdir / f"{out_prefix}_metrics.json"

    # ------------------------------------------------------------------
    # Pass 1: timing stats (--stats)
    # ------------------------------------------------------------------
    _run_rocprof_stats(
        rocprof_bin=rocprof_bin,
        benchmark_script=benchmark_script,
        workdir=workdir,
        out_csv=stats_csv,
        python_executable=python_executable,
        env=env,
        timeout=timeout,
    )

    # ------------------------------------------------------------------
    # Pass 2: hardware PMC counters (-i input.txt)
    # ------------------------------------------------------------------
    input_file = _write_rocprof_input(workdir)
    _run_rocprof_pmc(
        rocprof_bin=rocprof_bin,
        benchmark_script=benchmark_script,
        workdir=workdir,
        input_file=input_file,
        out_csv=pmc_csv,
        python_executable=python_executable,
        env=env,
        timeout=timeout,
    )

    # ------------------------------------------------------------------
    # Merge outputs into metrics JSON
    # ------------------------------------------------------------------
    metrics = _merge_rocprof_outputs(stats_csv, pmc_csv)
    metrics_json.write_text(json.dumps(metrics, indent=2))

    print(f"[rocprof] Metrics written: {metrics_json}")
    return metrics_json


def _run_rocprof_stats(
    rocprof_bin: str,
    benchmark_script: Path,
    workdir: Path,
    out_csv: Path,
    python_executable: str,
    env: dict,
    timeout: int,
) -> None:
    """Run rocprof --stats to collect kernel timing."""
    # rocprofv3 requires --kernel-trace for --stats to work
    is_v3 = "rocprofv3" in rocprof_bin
    cmd = [rocprof_bin]
    if is_v3:
        cmd.extend(["--kernel-trace", "--stats", "-o", str(out_csv)])
    else:
        cmd.extend(["--stats", "-o", str(out_csv)])
    cmd.extend(["--", python_executable, str(benchmark_script)])
    print(f"[rocprof] Running stats: {' '.join(cmd[:6])}...")
    result = subprocess.run(
        cmd,
        cwd=str(workdir),
        env=env,
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"rocprof --stats failed (rc={result.returncode}):\n"
            f"{(result.stderr or result.stdout)[:500]}"
        )
    print("[rocprof] Stats pass completed")


def _run_rocprof_pmc(
    rocprof_bin: str,
    benchmark_script: Path,
    workdir: Path,
    input_file: Path,
    out_csv: Path,
    python_executable: str,
    env: dict,
    timeout: int,
) -> None:
    """Run rocprof -i <input_file> to collect PMC counters."""
    # rocprofv3 uses --pmc or -i for counter collection
    cmd = [
        rocprof_bin,
        "-i",
        str(input_file),
        "-o",
        str(out_csv),
        "--",
        python_executable,
        str(benchmark_script),
    ]
    print(f"[rocprof] Running PMC counters: {' '.join(cmd[:6])}...")
    result = subprocess.run(
        cmd,
        cwd=str(workdir),
        env=env,
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"rocprof PMC pass failed (rc={result.returncode}):\n"
            f"{(result.stderr or result.stdout)[:500]}"
        )
    print("[rocprof] PMC pass completed")


# ---------------------------------------------------------------------------
# Output parsing
# ---------------------------------------------------------------------------


def _parse_stats_csv(csv_path: Path) -> Dict[str, Any]:
    """Parse rocprof --stats CSV to extract kernel durations."""
    if not csv_path.exists():
        return {}

    import csv

    rows: List[Dict[str, str]] = []
    try:
        with csv_path.open(newline="") as f:
            reader = csv.DictReader(f)
            rows = list(reader)
    except Exception:
        return {}

    if not rows:
        return {}

    # rocprof stats CSV columns: Name, Calls, TotalDurationNs, AverageNs, ...
    # Pick the last kernel invocation (after warmup)
    row = rows[-1]
    result: Dict[str, Any] = {}
    for key in ("Name", "Calls", "TotalDurationNs", "AverageNs", "Percentage"):
        if key in row:
            try:
                result[key.lower()] = float(row[key]) if key != "Name" else row[key]
            except (ValueError, TypeError):
                result[key.lower()] = row[key]

    if "averagens" in result:
        result["duration_ns"] = result["averagens"]
        result["duration_ms"] = result["averagens"] / 1e6

    return result


def _parse_pmc_csv(csv_path: Path) -> Dict[str, Any]:
    """Parse rocprof PMC CSV to extract hardware counter values."""
    if not csv_path.exists():
        return {}

    import csv

    rows: List[Dict[str, str]] = []
    try:
        with csv_path.open(newline="") as f:
            reader = csv.DictReader(f)
            rows = list(reader)
    except Exception:
        return {}

    if not rows:
        return {}

    # rocprof PMC CSV columns: Index, KernelName, gpu-id, queue-id,
    # queue-index, pid, tid, grd, wgr, lds, scr, arch_vgpr, accum_vgpr,
    # sgpr, wave_size, sig, obj, <counter1>, <counter2>, ...
    # Aggregate all rows by summing numeric counter columns
    aggregated: Dict[str, float] = {}
    counter_cols = [
        k
        for k in rows[0].keys()
        if k
        not in (
            "Index",
            "KernelName",
            "gpu-id",
            "queue-id",
            "queue-index",
            "pid",
            "tid",
            "sig",
            "obj",
        )
    ]

    for row in rows:
        for col in counter_cols:
            try:
                aggregated[col] = aggregated.get(col, 0.0) + float(row[col])
            except (ValueError, TypeError, KeyError):
                pass

    return aggregated


def _merge_rocprof_outputs(
    stats_csv: Path,
    pmc_csv: Path,
) -> Dict[str, Any]:
    """Merge stats and PMC outputs into a normalized metrics dictionary.

    The returned dict is compatible with the rest of the KernelAgent pipeline
    (same structure expected by RooflineAnalyzer and BottleneckAnalyzer).
    """
    stats = _parse_stats_csv(stats_csv)
    pmc = _parse_pmc_csv(pmc_csv)

    # Raw counters (lower-cased for consistency)
    raw: Dict[str, Any] = {}
    for k, v in pmc.items():
        raw[k.lower()] = v

    # Normalize to our metric keys
    metrics: Dict[str, Any] = {
        "sq_waves": raw.get("sq_waves", 0.0),
        "sq_insts_valu": raw.get("sq_insts_valu", 0.0),
        "sq_insts_salu": raw.get("sq_insts_salu", 0.0),
        "sq_insts_vmem_rd": raw.get("sq_insts_vmem_rd", 0.0),
        "sq_insts_vmem_wr": raw.get("sq_insts_vmem_wr", 0.0),
        "sq_insts_lds": raw.get("sq_insts_lds", 0.0),
        "sq_wait_inst_any": raw.get("sq_wait_inst_any", 0.0),
        "tcc_hit": raw.get("tcc_hit_sum", 0.0),
        "tcc_miss": raw.get("tcc_miss_sum", 0.0),
        "tcc_ea_rdreq": raw.get("tcc_ea_rdreq_sum", 0.0),
        "tcc_ea_wrreq": raw.get("tcc_ea_wrreq_sum", 0.0),
        "fetch_size_kb": raw.get("fetch_size", 0.0),
        "write_size_kb": raw.get("write_size", 0.0),
        # Timing from stats pass
        "duration_ms": stats.get("duration_ms", 0.0),
    }

    # Derived: L2 cache hit rate
    tcc_total = metrics["tcc_hit"] + metrics["tcc_miss"]
    metrics["tcc_cache_hit_rate_pct"] = (
        100.0 * metrics["tcc_hit"] / tcc_total if tcc_total > 0 else 0.0
    )

    # Derived: VALU utilization (fraction of cycles spent on vector ALU)
    total_insts = (
        metrics["sq_insts_valu"]
        + metrics["sq_insts_salu"]
        + metrics["sq_insts_vmem_rd"]
        + metrics["sq_insts_vmem_wr"]
        + metrics["sq_insts_lds"]
    )
    metrics["valu_utilization_pct"] = (
        100.0 * metrics["sq_insts_valu"] / total_insts if total_insts > 0 else 0.0
    )

    # Derived: memory-bound heuristic — fraction of instructions that are memory ops
    vmem_insts = metrics["sq_insts_vmem_rd"] + metrics["sq_insts_vmem_wr"]
    metrics["memory_bound_pct"] = (
        100.0 * vmem_insts / total_insts if total_insts > 0 else 0.0
    )

    # Derive roofline-compatible SOL estimates from counter ratios.
    # These are heuristic approximations since rocprof does not provide
    # "Speed of Light" metrics directly (unlike NCU).
    #
    # Compute SOL: use VALU utilization as a proxy for compute utilization.
    # Memory SOL: use cache miss rate × memory traffic as a bandwidth proxy.
    # Both are normalized to [0, 100].
    metrics["compute_sol_pct"] = min(metrics["valu_utilization_pct"], 100.0)
    metrics["memory_sol_pct"] = min(metrics["memory_bound_pct"], 100.0)

    # Include raw counter dump for debugging / LLM consumption
    metrics["_raw_counters"] = {k: v for k, v in raw.items()}

    return metrics


# ---------------------------------------------------------------------------
# Public helper: load metrics from a previously written JSON file
# ---------------------------------------------------------------------------


def load_rocm_metrics(json_path: Path) -> Dict[str, Any]:
    """Load rocprof metrics from a JSON file produced by :func:`profile_triton_kernel_rocm`.

    Args:
        json_path: Path to the JSON file.

    Returns:
        Metrics dictionary.

    Raises:
        FileNotFoundError: If the file does not exist.
    """
    if not json_path.exists():
        raise FileNotFoundError(f"ROCm metrics JSON not found: {json_path}")
    return json.loads(json_path.read_text())


def metrics_to_prompt_rocm(metrics: Dict[str, Any]) -> str:
    """Convert ROCm metrics dict to a JSON string for LLM prompts.

    Args:
        metrics: Metrics dictionary from :func:`load_rocm_metrics`.

    Returns:
        JSON string (drops internal ``_raw_counters`` key for brevity).
    """
    # Exclude raw counter dump from LLM context (too verbose)
    filtered = {k: v for k, v in metrics.items() if k != "_raw_counters"}
    return json.dumps(filtered, indent=2)
